### PR TITLE
Fixed unicode usage for python 3

### PR DESCRIPTION
**Pull request by farkasgy**
The following commit fixes issue #9 and also another problem related to DateTime usage

### CODE REVIEW

**Comment by andreif** [comment]
@farkasgy I had to change it a bit to make caching work https://github.com/andreif/suds-py3/commit/516237441ad472375ce6b31d4f5b7c4a5a2d6db8

**Comment by andreif** [comment]
@farkasgy I have created farkasgy#1 to fix few more issues. Let me know if you have time to look at it. Otherwise I can create a combined PR here, @cackharot

**Comment by andreif** [comment]
I needed the fixes for testing another package so I created a temporary PyPI distribution: https://pypi.python.org/pypi/suds-py3-fixes

**Comment by cackharot** [comment]
Thanks for your effort. Much apperciated.

**Comment by andreif** [comment]
@cackharot I have opened #12 with fixes from farkasgy#1.

**Pull request merged**
