### PR TITLE
Extra fixes for #11

### PR DESCRIPTION
**Pull request by andreif**
Related to #11

### CODE REVIEW

**Comment by cackharot** [comment]
Thanks!

This is published at https://pypi.python.org/pypi?:action=display&name=suds-py3&version=1.3.0.0

**Comment by andreif** [comment]
@cackharot Awesome, exactly what I was going to ask for :+1:

**Comment by andreif** [comment]
@cackharot I've just noticed that `1.3` tag points to an older commit but I think it's better to move it to 25f9f914 if it's included in 1.3.0.0 on pypi.

**Comment by andreif** [comment]
@cackharot I have broken schema unfortunately, very sorry. Better to move tag after #13 is merged.

**Pull request merged**
